### ISSUE TITLE
Add documentation for configuration and triggering

### ISSUE THREAD

**Issue by markphip** [GerritForge/gerrit-plugin#2]
Giving this a try, sort of got it working.  However, I am not clear how you are supposed to trigger new builds when reviews are posted?  Elsewhere, you have said it is done with webhooks but what URL are you sending it to?  I tried sending the hook to:

http://<jenkins host>:<jenkins port>/gerrit-hook/

But this did not work for me.  Wouldn't the jobname need to be in the URL somewhere too?  Are there any other Jenkins plugins needed to install for this like their Generic webhook plugin?

Finally, in the example you show how to cast a verified vote.  What is less clear is what is available to condition this behavior?  Presumably you also want to use Jenkinsfile to do a "production" build off master.  What conditional techniques do you envisioning using inside the Jenkinsfile so you know the difference as to when it is running a job to verify a review, and should cast a vote, as opposed to a production type build where you do not want a vote?

**Comment by KenjiTakahashi** [comment]
FYI (and others), as I was working on this today as well.

First, the correct endpoint is `gerrit-webhook/`, **not** `gerrit-hook/`. [Also, the slash at the end seems important, not sure why, though.]
Second, CSRF protection might be catching you in the middle.
Third, the user with which you authenticate in the hook request needs to have permissions to list jobs.

Also, there seems to be some kind of "off by 1" bug on one side (not sure which), that causes Content-Length to sometimes be 1 larger than the actual length...

Still no luck, as I'm now getting some git/ssh related errors ;-).

**Comment by lucamilanesio** [comment]
@markphip there are no extra Jenkins plugins needed: the /gerrit-webhook/ endpoint is included in this plugin already.
On the Gerrit side, you will need the webhooks plugin and configure the relevant project.config.

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
