### ISSUE TITLE
document configuration for jobs without Jenkinsfile stored inside repository

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#3]
We need to document how a scriptable pipeline using gerrit-plugin should look.

For start this is how the most basic JJB pipeline job definition looks like (dsl is exactly the body of the pipeline):

```
---
- job:
    name: 'foobar'
    project-type: pipeline
    dsl: |
        node('master') {
            stage('build') {
              sh "true"
         }
        }
```

Background information: Some organizations are using Jenkins pipelines without adding the pipeline inside the repository. Instead they do build and upload these pipelines to Jenkins using tools like [jenkins-job-builder](https://docs.openstack.org/infra/jenkins-job-builder/) (jjb), this being a preferred way to keep pipeline codes in a single secured repository and avoiding polluting each component with CI code. Just to give an impression of scale: >50 component repositories and >1000 pipeline jobs defined for there (most of them gates).

**Comment by lucamilanesio** [comment]
Yes, agreed. We do the same with the Gerrit-CI on gerrit-ci.gerritforge.com.

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
