### ISSUE TITLE
add gerrit plugin support into jjb (jenkins-job-builder)

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#4]
Feel free to assign this ticket to me, I am working on adding multibranch+gerrit folder support on jjb, support that will include gerrit plugin support. I am very close from raising a CRs on JJB that enables this.

Once I have this done, I will also add documentation on how to use it. I will post links here with the progress.

**Comment by lucamilanesio** [comment]
That is *really cool* and thanks @ssbarnea for working on it. Your work is going to be the __missing bit__ we need to migrate to this new plugin on gerrit-ci.gerritforge.com

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
