### ISSUE TITLE
abandoned change request detected and builded instead of being skipped

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#5]
It seems that gerrit plugin managed to detect a CR that was Abandoned long time ago and it did create a branch for it and builded it. This should not happen, nobody wants to build abandoned reviews.

This also raises the question regarding when a CR branch should be removed from Jenkins. Clearly we do not want an ever growing list of branches. 

Do we want to removed merged changes as soon they are detected? How about abandoned ones?

We can assume that a CR that is not abandoned and not merged should be kept because Gerrit project owner can decide to remove of abandon them, even if they are not raised by himself. I think that is better for Jenkins to follow Gerrit on this.

**Comment by lucamilanesio** [comment]
This has been already resolved on master. Changes that are not opened anymore are filtered out and won't be pulled and built by the pipeline.

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
