### ISSUE TITLE
Could not fetch branches from source - org.eclipse.jgit.errors.MissingObjectException: Missing unknown 

### ISSUE THREAD

**Issue by ssbarnea** [GerritForge/gerrit-plugin#7]
It seems that Gerrit plugin failed to correctly get new changes from gerrit. Somehow branch indexing failed. Full log at https://gist.github.com/ssbarnea/740c88ec3c6488bdb36fb3bfbc144b09#file-gerrit-plugin-branch-indexing-log-L43

The new change `Checking change 93/127593/2` was detected but it failed to pull it:
```
ERROR: [Thu Jan 18 21:25:19 UTC 2018] Could not fetch branches from source f2a102e5-dcbb-42ec-8733-51eadbadca9a
org.eclipse.jgit.errors.MissingObjectException: Missing unknown f67d9d034c47bc2d62827095845822897df78db1
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:158)
```

I mention that there is nothing wrong or special about the test repository. In fact this additional patchset was created specially to test the detection of new changes.

The problems seems similar to https://issues.jenkins-ci.org/browse/JENKINS-45729 but it happens to me while using latest git plugin 3.7.0 and that bug reports it as sorted in 3.6.0

**Comment by ssbarnea** [comment]
Found the culprit. It seems that the default refspecs used are not wide enough to get all changes. By adding the `+refs/heads/*:refs/remotes/@{remote}/*` refspec in the plugin config, it started to find all changes.

Still, the bug is perfectly valid because the default respect should include these and not force the user to configure that option himself.

**Comment by lucamilanesio** [comment]
Yes, the plugin doesn't check at the moment that the refspecs requested are matching the expected SHA1s and you get the "missing unknown" error.

__P.S. Closing this issue as this repo is going to be dismissed. Any further issues need to be raised on issues.jenkins-ci.org__
